import type { District, Store, Product, Movement } from "./types"

export const districts: District[] = [
  { id: "dist-1", name: "КШТ" },
  { id: "dist-2", name: "Потанина" },
  { id: "dist-3", name: "Согра" },
]

export const stores: Store[] = [
  { id: "store-1", districtId: "dist-1", name: "Магазин Центральный", address: "ул. Ленина, 15" },
  { id: "store-2", districtId: "dist-1", name: "Магазин Северный", address: "пр. Мира, 42" },
  { id: "store-3", districtId: "dist-2", name: "Потанина (общий)", address: "ул. Гагарина, 8" },
  { id: "store-4", districtId: "dist-3", name: "Согра (общий)", address: "ул. Пушкина, 23" },
]

export const products: Product[] = [
  { id: "prod-1", name: "Корн-дог классический", costPrice: 25, salePrice: 45 },
  { id: "prod-2", name: "Корн-дог с сыром", costPrice: 30, salePrice: 55 },
  { id: "prod-3", name: "Корн-дог XXL", costPrice: 35, salePrice: 65 },
]

const today = new Date()
const getDate = (daysAgo: number) => {
  const d = new Date(today)
  d.setDate(d.getDate() - daysAgo)
  return d
}

export const initialMovements: Movement[] = [
  {
    id: "mov-1",
    date: getDate(0),
    districtId: "dist-1",
    storeId: "store-1",
    productId: "prod-1",
    operationType: "sale",
    quantity: 50,
    unitPrice: 45,
    comment: "Утренняя поставка",
  },
  {
    id: "mov-2",
    date: getDate(0),
    districtId: "dist-1",
    storeId: "store-2",
    productId: "prod-1",
    operationType: "sale",
    quantity: 35,
    unitPrice: 45,
  },
  {
    id: "mov-3",
    date: getDate(0),
    districtId: "dist-2",
    storeId: "store-3",
    productId: "prod-2",
    operationType: "sale",
    quantity: 40,
    unitPrice: 55,
  },
  {
    id: "mov-4",
    date: getDate(1),
    districtId: "dist-1",
    storeId: "store-1",
    productId: "prod-1",
    operationType: "sale",
    quantity: 60,
    unitPrice: 45,
    comment: "Большой заказ",
  },
  {
    id: "mov-5",
    date: getDate(1),
    districtId: "dist-1",
    storeId: "store-2",
    productId: "prod-2",
    operationType: "sale",
    quantity: 25,
    unitPrice: 55,
  },
  {
    id: "mov-6",
    date: getDate(1),
    districtId: "dist-3",
    storeId: "store-4",
    productId: "prod-3",
    operationType: "sale",
    quantity: 30,
    unitPrice: 65,
  },
  {
    id: "mov-7",
    date: getDate(2),
    districtId: "dist-1",
    storeId: "store-1",
    productId: "prod-1",
    operationType: "return",
    quantity: 5,
    unitPrice: 45,
    comment: "Брак",
  },
  {
    id: "mov-8",
    date: getDate(2),
    districtId: "dist-2",
    storeId: "store-3",
    productId: "prod-1",
    operationType: "sale",
    quantity: 45,
    unitPrice: 45,
  },
  {
    id: "mov-9",
    date: getDate(2),
    districtId: "dist-1",
    storeId: "store-2",
    productId: "prod-3",
    operationType: "exchange",
    quantity: 10,
    unitPrice: 65,
    comment: "Замена партии",
  },
  {
    id: "mov-10",
    date: getDate(3),
    districtId: "dist-3",
    storeId: "store-4",
    productId: "prod-2",
    operationType: "sale",
    quantity: 55,
    unitPrice: 55,
  },
  {
    id: "mov-11",
    date: getDate(3),
    districtId: "dist-1",
    storeId: "store-1",
    productId: "prod-3",
    operationType: "sale",
    quantity: 20,
    unitPrice: 65,
  },
  {
    id: "mov-12",
    date: getDate(4),
    districtId: "dist-1",
    storeId: "store-2",
    productId: "prod-1",
    operationType: "sale",
    quantity: 70,
    unitPrice: 45,
  },
  {
    id: "mov-13",
    date: getDate(4),
    districtId: "dist-2",
    storeId: "store-3",
    productId: "prod-2",
    operationType: "return",
    quantity: 8,
    unitPrice: 55,
    comment: "Просрочка",
  },
  {
    id: "mov-14",
    date: getDate(5),
    districtId: "dist-1",
    storeId: "store-1",
    productId: "prod-1",
    operationType: "sale",
    quantity: 40,
    unitPrice: 45,
  },
  {
    id: "mov-15",
    date: getDate(5),
    districtId: "dist-3",
    storeId: "store-4",
    productId: "prod-1",
    operationType: "sale",
    quantity: 55,
    unitPrice: 45,
  },
  {
    id: "mov-16",
    date: getDate(6),
    districtId: "dist-1",
    storeId: "store-2",
    productId: "prod-2",
    operationType: "sale",
    quantity: 35,
    unitPrice: 55,
  },
  {
    id: "mov-17",
    date: getDate(6),
    districtId: "dist-2",
    storeId: "store-3",
    productId: "prod-3",
    operationType: "sale",
    quantity: 25,
    unitPrice: 65,
  },
  {
    id: "mov-18",
    date: getDate(7),
    districtId: "dist-1",
    storeId: "store-1",
    productId: "prod-2",
    operationType: "exchange",
    quantity: 15,
    unitPrice: 55,
    comment: "По договорённости",
  },
  {
    id: "mov-19",
    date: getDate(1),
    districtId: "dist-2",
    storeId: "store-3",
    productId: "prod-1",
    operationType: "bonus",
    quantity: 10,
    unitPrice: 0,
    comment: "Бонус за объём",
  },
  {
    id: "mov-20",
    date: getDate(3),
    districtId: "dist-3",
    storeId: "store-4",
    productId: "prod-2",
    operationType: "bonus",
    quantity: 5,
    unitPrice: 20,
    comment: "Промо-акция",
  },
  {
    id: "mov-21",
    date: getDate(0),
    districtId: "dist-2",
    storeId: null,
    productId: "prod-1",
    operationType: "sale",
    quantity: 30,
    unitPrice: 45,
    comment: "Оптовая по району",
  },
]
